### ISSUE TITLE
Blank ebook pages on gutenberg.org

### ISSUE THREAD

**Issue by mrcook** [gutenbergtools/ebookconverter#43]
I've encountered 4 missing ebooks from the gutenberg website: `38200`, `57983`, `64156`, `65643`. These pages contain no data, and only have a link to the RDF file. I discovered these because the RDF files also have blank data.

In the July 2021 newsletter, [65643](https://www.gutenberg.org/ebooks/65643) is listed as, "_The lives of celebrated travellers, Vol. 2, by James Augustus St. John_"

Related, but I guess not an eText release is ID `90907`, which  exists in the `rdf-files.tar.zip` offline archive, and also contains blank data.

P.S. I wasn't sure where to raise this issue so please point me to the correct place if needed.

**Comment by eshellman** [comment]
I keep a list of etext numbers that are "missing" or should be excluded from various processes

https://github.com/gitenberg-dev/gitberg/blob/master/gitenberg/data/missing.tsv
> 38200,  
> 
removed due to copyright issues

> 57983, 
> 
unused
> 64156, 
> 
unused
> 65643
> 

missing

PG has no workflow for voiding an etext number and it happens for various reasons on an ad hoc basis. This is an appropriate place for the issue; as code here implements a number of related workflows. However, there are a number of informal workflows involved, and it's not clear that it's an urgent problem for anyone.

Eric

**Comment by mrcook** [comment]
Thanks Eric. As they're all known then I'll close the ticket.
